### PR TITLE
fixed some of the nav bar elements (fixed the logo to navigate to home page) new feature of loading home page of 1second designed about page

### PR DESCRIPTION
**Pull request by Rtarun3606k**
What does this PR do?
This PR (fixed the logo to navigate to home page) and add some new feratures:

Designed About Page
added a blur transition while navigating from one page to other (highly recommed to check)
#86 

  
Screenshot (147)

from this to 

Screenshot (149)

designed about page

Screenshot (148)

happy coding

### CODE REVIEW

**Comment by Rtarun3606k** [comment]
What does this PR do?
This PR (fixed the logo to navigate to home page) and add some new feratures:

Designed About Page
added a blur transition while navigating from one page to other (highly recommed to check)
#86 

  
Screenshot (147)


from this to 

Screenshot (149)



designed about page


Screenshot (148)

happy coding

**Comment by BidyasagarAnupam** [comment]
Do change relevant things only for the About page...

**Comment by Rtarun3606k** [comment]
Give some info to add in about page

**Comment by Rtarun3606k** [comment]
> Do change relevant things only for the About page... 

Give some info to add in about page

**Comment by Rtarun3606k** [comment]
> Write about MCA at NIT JSR

Is there anything more like some events at nit to be more like events, etc. to mention in about page

**Pull request closed without merging**
